[package]
name = "cargo_intro"
version = "0.1.0"
authors = ["Osifo Anosike <code.anosikeosifo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
